//go:build !lib

// Source mode: compile C sources directly with CGO.
// Usage: go build (default)
// Requires: CGO_CFLAGS_ALLOW="-mavx.*|-msse.*|-mfma|-mavx512.*"
// Generated by CMake - DO NOT EDIT MANUALLY
package exchange

/*
#cgo CFLAGS: -I${SRCDIR}/include
#cgo CFLAGS: -I${SRCDIR}/modules/platform/include
#cgo CFLAGS: -I${SRCDIR}/modules/ds/include
#cgo CFLAGS: -I${SRCDIR}/modules/sort/include
#cgo CFLAGS: -I${SRCDIR}/modules/stats/include
#cgo CFLAGS: -I${SRCDIR}/modules/math/include
#cgo CFLAGS: -I${SRCDIR}/exchange-c
#cgo CFLAGS: -I${SRCDIR}/modules/platform/src -O2 -Wall -std=c11 -mavx2 
#cgo linux CFLAGS: -D_POSIX_C_SOURCE=200112L
#cgo linux LDFLAGS: ${SRCDIR}/modules/platform/build/linux_amd64/libfinkit_platform_static.a -lm -lgcov
#cgo darwin,arm64 LDFLAGS: ${SRCDIR}/modules/platform/build/darwin_arm64/libfinkit_platform_static.a -lm
#cgo darwin,amd64 LDFLAGS: ${SRCDIR}/modules/platform/build/darwin_x86_64/libfinkit_platform_static.a -lm
#cgo windows LDFLAGS: ${SRCDIR}/modules/platform/build/windows_amd64/libfinkit_platform_static.a -lm

#cgo linux LDFLAGS: ${SRCDIR}/modules/ds/build/linux_amd64/libfinkit_ds_static.a -lm -lgcov
#cgo darwin,arm64 LDFLAGS: ${SRCDIR}/modules/ds/build/darwin_arm64/libfinkit_ds_static.a -lm
#cgo darwin,amd64 LDFLAGS: ${SRCDIR}/modules/ds/build/darwin_x86_64/libfinkit_ds_static.a -lm
#cgo windows LDFLAGS: ${SRCDIR}/modules/ds/build/windows_amd64/libfinkit_ds_static.a -lm
#cgo windows LDFLAGS: ${SRCDIR}/modules/ds/build/windows_amd64/libfinkit_ds_static.a -lm

#cgo linux LDFLAGS: ${SRCDIR}/modules/sort/build/linux_amd64/libfinkit_sort_static.a -lm -lgcov
#cgo darwin,arm64 LDFLAGS: ${SRCDIR}/modules/sort/build/darwin_arm64/libfinkit_sort_static.a -lm
#cgo darwin,amd64 LDFLAGS: ${SRCDIR}/modules/sort/build/darwin_x86_64/libfinkit_sort_static.a -lm
#cgo windows LDFLAGS: ${SRCDIR}/modules/sort/build/windows_amd64/libfinkit_sort_static.a -lm

#cgo linux LDFLAGS: ${SRCDIR}/modules/stats/build/linux_amd64/libfinkit_stats_static.a -lm -lgcov
#cgo darwin,arm64 LDFLAGS: ${SRCDIR}/modules/stats/build/darwin_arm64/libfinkit_stats_static.a -lm
#cgo darwin,amd64 LDFLAGS: ${SRCDIR}/modules/stats/build/darwin_x86_64/libfinkit_stats_static.a -lm
#cgo windows LDFLAGS: ${SRCDIR}/modules/stats/build/windows_amd64/libfinkit_stats_static.a -lm

#cgo linux LDFLAGS: ${SRCDIR}/modules/math/build/linux_amd64/libfinkit_math_static.a -lm -lgcov
#cgo darwin,arm64 LDFLAGS: ${SRCDIR}/modules/math/build/darwin_arm64/libfinkit_math_static.a -lm
#cgo darwin,amd64 LDFLAGS: ${SRCDIR}/modules/math/build/darwin_x86_64/libfinkit_math_static.a -lm
#cgo windows LDFLAGS: ${SRCDIR}/modules/math/build/windows_amd64/libfinkit_math_static.a -lm

#include "exchange.h"
#include "ticker.h"
#include "ticker_merge.h"
#include "generic_ring_buffer.h"
#include "orderbook.h"
#include "market_indicators.h"
#include "market_maker_quotes.h"


// Exchange sources
#include "exchange-c/ticker.c"
#include "exchange-c/ticker_merge.c"
#include "exchange-c/orderbook.c"
#include "exchange-c/market_indicators.c"
#include "exchange-c/market_maker_quotes.c"

int fc_init(void);
void fc_cleanup(void);
*/
import "C"

func init() {
	C.fc_init()
}
